@startuml

left to right direction

package de.thro.inf.prg3.a09.resource {

	class de.thro.inf.prg3.a09.model.FxImageLoaderAdapter {
		- resourceLoader: ResourceLoader<Image>
		+ loadImage(resourcePath: String)
		+ loadImage(resourceContext: ClassLoader, resourcePath: String)
	}

	class ResourceLoader<T> {
		+ loadResource(resourceContext: ClassLoader, path: String): T
	}

	de.thro.inf.prg3.a09.model.FxImageLoaderAdapter *-- ResourceLoader
}
@enduml
